const MenuConfig = {
  '/':[
    {
      cn:'婚纱摄影',
      en:'PHOTO',
      link:'/shot',
      target:false,
      kClass:'item primary'
    },
    {
      cn:'婚庆定制',
      en:'WEDDING',
      link:'/scheme',
      target:false,
      kClass:'item primary'
    },
    {
      cn:'旅拍',
      en:'TRIP',
      link:'http://trip.jsbn.com',
      target:true,
      kClass:'item primary'
    },
    {
      cn:'婚宴预订',
      en:'BANQUET',
      link:'/hotel',
      target:false,
      kClass:'item secondary'
    },
    {
      cn:'婚戒钻石',
      en:'DIAMOND',
      link:'http://www.chinad9.com',
      target:true,
      kClass:'item secondary'
    }
  ],
  '/home':[
    {
      cn:'婚纱摄影',
      en:'PHOTO',
      link:'/shot',
      target:false,
      kClass:'item primary'
    },
    {
      cn:'婚庆定制',
      en:'WEDDING',
      link:'/scheme',
      target:false,
      kClass:'item primary'
    },
    {
      cn:'旅拍',
      en:'TRIP',
      link:'http://trip.jsbn.com',
      target:true,
      kClass:'item primary'
    },
    {
      cn:'婚宴预订',
      en:'BANQUET',
      link:'/hotel',
      target:false,
      kClass:'item secondary'
    },
    {
      cn:'婚戒钻石',
      en:'DIAMOND',
      link:'http://www.chinad9.com',
      target:true,
      kClass:'item secondary'
    }
  ],
  '/shot':[
    {
      cn:'全站首页',
      en:'HOME',
      link:'/',
      target:false
    },
    {
      cn:'婚纱摄影首页',
      en:'PHOTO',
      link:'/shot',
      target:false
    },
    {
      cn:'作品欣赏',
      en:'WORKS',
      link:'/sample',
      target:false
    },
    {
      cn:'客片欣赏',
      en:'PRINGLES',
      link:'/pringles',
      target:false
    },
    {
      cn:'套系报价',
      en:'SUITE',
      link:'/suite',
      target:false
    },
    //{
    //  cn:'婚纱纪实',
    //  en:'MV',
    //  link:'/weddingmv',
    //  target:false
    //},
    {
      cn:'微电影',
      en:'MOVIE',
      link:'/movie',
      target:false
    }
  ],
  '/hotel':[
    {
      cn:'全站首页',
      en:'HOME',
      link:'/',
      target:false
    },
    {
      cn:'婚宴预订首页',
      en:'BANQUET',
      link:'/hotel',
      target:false
    },
    {
      cn:'提交需求',
      en:'REQUIRE',
      link:'/hotel-require',
      target:false
    },
    {
      cn:'大礼包',
      en:'GIFT',
      link:'/activity/detail/libao',
      target:false
    }
  ],
  '/scheme':[
    {
      cn:'全站首页',
      en:'HOME',
      link:'/',
      target:false
    },
    {
      cn:'婚庆首页',
      en:'WEDDING',
      link:'/scheme',
      target:false
    },
    {
      cn:'实景案例',
      en:'CASES',
      link:'/cases',
      target:false
    },
    {
      cn:'婚礼跟拍',
      en:'FOLLOW',
      link:'/weddingpat',
      target:false
    },
    {
      cn:'婚礼视频',
      en:'VIDEO',
      link:'/weddingvideo',
      target:false
    },
    {
      cn:'选婚礼人',
      en:'F4',
      link:'/f4',
      target:false
    },
    {
      cn:'婚纱礼服',
      en:'DRESS',
      link:'/dress',
      target:false
    },
    {
      cn:'婚礼用品',
      en:'SUPPLIES',
      link:'/supply',
      target:false
    },
    {
      cn:'婚车租赁',
      en:'CAR',
      link:'/car',
      target:false
    }
  ]
}

export { MenuConfig }
